### ISSUE TITLE
Windows installation error: django.core.exceptions.ImproperlyConfigured

### ISSUE THREAD

**Issue by maltaesousa** [opengisch/OpenComptage#151]
On windows, plugin cannot be loaded:
```
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings. 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\__init__.py", line 30, in classFactory
    from .comptages import Comptages
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\comptages.py", line 19, in 
    from comptages.importer.data_importer_vbv1 import DataImporterVbv1
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\importer\data_importer_vbv1.py", line 5, in 
    from comptages.datamodel import models
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\datamodel\models.py", line 8, in 
    class Brand(models.Model):
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\django\apps\registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\django\apps\registry.py", line 135, in check_apps_ready
    settings.INSTALLED_APPS
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\django\conf\__init__.py", line 63, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.20.0-Odense Odense, decaadbb31 
```

Did I miss something during install?

**Comment by marioba** [comment]
Is this with the last version v0.9.2?

**Comment by maltaesousa** [comment]
It was with v0.9.0 but with v0.9.2 it's the same. I'm available with TeamViewer + Google Meet or Zoom if you want to check our environment

**Comment by marioba** [comment]
At what point do you have this error?

**Comment by maltaesousa** [comment]
When I open QGIS. The plugin doesn't load:
```
Impossible de charger l'extension 'comptages' provoque une erreur lors de l'appel à sa méthode classFactory() 
```

**Comment by marioba** [comment]
Let me know when do you have time to have a look together...
