### ISSUE TITLE
Installation - Development version - Windows - importsections

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#155]
j'ai des problèmes avec cette dernière étape:

1. il faut copier le dossier db dans celui des plugins sinon: `django.contrib.gis.gdal.error.GDALException: Could not open the datasource at "C:\Users/grelletp/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev_dock/python/plugins\comptages\datamodel\management\commands\..\..\..\..\db\sections_clean.csv"`
2. malgré cela, le script ne fonctionne pas: 
Importing sections...
```
Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "section" does not exist
LINE 1: INSERT INTO "section" ("id", "name", "owner", "road", "way",...
                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users/grelletpadm/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev_dock/python/plugins\comptages\datamodel\management\commands\importsections.py", line 51, in handle
    Section.objects.bulk_create(sections)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 502, in bulk_create
    returned_columns = self._batched_insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1287, in _batched_insert
    inserted_rows.extend(self._insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "section" does not exist
LINE 1: INSERT INTO "section" ("id", "name", "owner", "road", "way",...
                    ^
```

**Comment by marioba** [comment]
I was able to reproduce the problem. Migration 0002 defines "search_paths" in the database so that tables that are in the "comptages" schema are found. However, the connection to the database is already open at this point and is not being updated. 

Restarting QGIS after generating the database, before doing "importsections" seems to solve the problem.

**Comment by spch-GL** [comment]
Yes, sections are now imported correctly into SECTION
But LANE remains empty...

**Comment by spch-GL** [comment]
Il y a encore un petit souci: doublon présent !

```
call_command('importdata', '--clear')
Deleting...
Importing sections...
Inserted 8802 sections.
Importing brands...
Inserted 2 brands.
Importing categories...
Inserted 105 categories.
Importing classes...
Inserted 13 classes.
Importing class_categories...
Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "class_category_pkey"
DETAIL:  Key (id_class)=(2) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev_dock/python/plugins\comptages\datamodel\management\commands\importdata.py", line 45, in handle
    self.import_class_categories(self.file_path("class_category.csv"))
  File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev_dock/python/plugins\comptages\datamodel\management\commands\importdata.py", line 154, in import_class_categories
    ClassCategory.objects.bulk_create(class_categories)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 502, in bulk_create
    returned_columns = self._batched_insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1287, in _batched_insert
    inserted_rows.extend(self._insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "class_category_pkey"
DETAIL:  Key (id_class)=(2) already exists.
```

**Comment by marioba** [comment]
**If you are on a test environment**, try this one. It will delete the content of the tables before importing the initial data:
    
```python
from django.core.management import call_command
call_command('importdata', '--clear')

**Comment by spch-GL** [comment]
That's what i made...
In fact, the primary key of this table has changed ! 
Please check creation script constraint again
```
CREATE TABLE IF NOT EXISTS comptages.class_category
(
    id_class bigint NOT NULL,
    id_category bigint NOT NULL,
    CONSTRAINT class_category_pkey PRIMARY KEY (id_class),
    CONSTRAINT class_category_id_class_id_category_bad2f523_uniq UNIQUE (id_class, id_category),
    CONSTRAINT class_category_id_category_1ec550c3_fk_category_id FOREIGN KEY (id_category)
        REFERENCES comptages.category (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT class_category_id_class_064adb03_fk_class_id FOREIGN KEY (id_class)
        REFERENCES comptages.class (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        DEFERRABLE INITIALLY DEFERRED
)
```

**Comment by spch-GL** [comment]
for instance, it used to be
`    CONSTRAINT class_category_pkey PRIMARY KEY (id_class, id_category),`

**Comment by spch-GL** [comment]
Le script importdata ne génère plus d'erreur. Merci
