### ISSUE TITLE
ModuleNotFoundError: No module named 'qgis.gui.QgsRangeSlider' 

### ISSUE THREAD

**Issue by maltaesousa** [opengisch/OpenComptage#176]
Installing v0.9.8 raises this error when opening QGIS and OpenComptage is not loaded:

```
Impossible de charger l'extension 'comptages' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'qgis.gui.QgsRangeSlider' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\__init__.py", line 31, in classFactory
    from .comptages import Comptages
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\comptages.py", line 15, in 
    from comptages.core.filter_dialog import FilterDialog
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\filter_dialog.py", line 6, in 
    FORM_CLASS = get_ui_class('filter.ui')
  File "C:\Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\utils.py", line 30, in get_ui_class
    return loadUiType(ui_file_path)[0]
  File "C:\OSGeo4W/apps/qgis/./python\qgis\PyQt\uic\__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\PyQt5\uic\__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 110, in 
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgis.gui.QgsRangeSlider'


Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.20.3-Odense Odense, 495fbaec 

Chemin Python :
C:/OSGeo4W/apps/qgis/./python
C:/Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:/Users/Maltas/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Maltas\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SelvansGeo\tools
```

This is weird because I can open a python console and `from qgis.gui import QgsRangeSlider` works.

Available for a videocall

ping @spch-GL

**Comment by marioba** [comment]
I did a version without the QgsRangeSlider until I discover why it doesn't work on your computers.
