### ISSUE TITLE
call_command('importdata')

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#204]
J'ai remplacé 2 des fichiers dans basedata (device.csv et model.csv) par ceux ci-joints
[device.csv](https://github.com/opengisch/OpenComptage/files/7454025/device.csv)
[model.csv](https://github.com/opengisch/OpenComptage/files/7454026/model.csv)

Le script rouspète pour device mais semble tout importer, aurais-tu une idée du pourquoi ?
call_command('importdata')
Importing sections...
Inserted 8802 sections.
Importing brands...
Inserted 2 brands.
Importing categories...
Inserted 119 categories.
Importing classes...
Inserted 13 classes.
Importing class_categories...
Inserted 111 class categories.
Importing installations...
Inserted 8779 installations.
Importing lanes...
Inserted 17551 lanes.
Importing models...
Inserted 10 models.
Importing model classes...
Inserted 0 model classes.
Importing sensor types...
Inserted 3 sensor types.
Importing sensor type classes...
Inserted 20 sensor type classes.
Importing sensor type installations...
Inserted 8779 sensor type installations.
Importing sensor type models...
Inserted 10 sensor type models.
Importing devices...
Exception ignored on calling ctypes callback function: <function err_handler at 0x0000021E531FCAF0>
Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\contrib\gis\gdal\libgdal.py", line 109, in err_handler
    logger.error('GDAL_ERROR %d: %s', error_number, message)
  File "C:\apps\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 1589, in _log
    self.handle(record)
  File "C:\apps\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "C:\apps\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "C:\apps\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 952, in handle
    self.emit(record)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\utils\log.py", line 120, in emit
    message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\views\debug.py", line 352, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\views\debug.py", line 318, in get_traceback_data
    'settings': self.filter.get_safe_settings(),
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\views\debug.py", line 122, in get_safe_settings
    settings_dict[k] = self.cleanse_setting(k, getattr(settings, k))
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\conf\__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Inserted 118 devices.
Importing sectors...
Inserted 10 sectors.
🚓

**Comment by spch-GL** [comment]
Par ailleurs, n'est-il pas surprenant qu'un table importée ne contienne aucun enregistrement ? 
Inserted 0 model classes.

**Comment by marioba** [comment]
The 2 files work correctly. I'll also add them to the repository to have a better base.
The error seems unrelated to the import of those files. It happens all the time?

**Comment by marioba** [comment]
Files added to v0.10.0
I close the issue. Feel free to reopen it if error occurs again.
