### ISSUE TITLE
Rapport annuel

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#212]
J'ai pu importer sans soucis une année complète en une fois, les 723 fichiers de CTC (SITE = 00107695 / LOCATION = Evit. Corcelles), et cela a mis moins de 11 minutes dont environ 4 pour afficher les graphiques. 👍 
J'ai ensuite essayé de générer un rapport annuel SWISS10 pour l'année 2020, mais ça plante:
```
2021-11-10T10:48:04     INFO    2021-11-10 10:48:04.984780 - Generate yearly report action started
2021-11-10T10:51:36     WARNING    Traceback (most recent call last):
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\comptages.py", line 433, in do_yearly_report_action
              yearly_report_creator.run()
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\report\yearly_report_creator.py", line 37, in run
              merged_count_data = data_loader.load(merged_count_data)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\data\data_loader.py", line 63, in load
              count_data.month_data[date[1]] += day_data.total()
             IndexError: list index out of range
```

**Comment by spch-GL** [comment]
J'ai aussi testé le rapport annuel pour la mobilité douce, et là pas d'erreur, mais le rapport n'est pas encore complet...
