### ISSUE TITLE
0022_auto_20211217_0624.py : Doesn't show anything

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#244]
Après 15 minutes, toujours pas de pourcentage, ni rien d'autre
Mais la fenêtre de la console Python est figée, pas celle de QGIS. 
![image](https://user-images.githubusercontent.com/26377323/152332919-e918f4a0-0ca6-4e82-8062-e98631c2e7a8.png)

Où faut-il chercher l'avancement ?
Faut-il démarrer ce script différemment ?

**Comment by marioba** [comment]
Yes, it should print in directly in the console, but apparently it does it only at the end of all the job, so quite useless...

I'll have to think about something different.

**Comment by spch-GL** [comment]
Ca s'est terminé ainsi:
```
Applying comptages.0022_auto_20211217_0624...starting logger
Start with count_aggregate_value_cls table
Total rows: 1799760
0
...
532000
Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\operations\special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_TST/python/plugins\comptages\datamodel\migrations\0022_auto_20211217_0624.py", line 48, in migrate_data
    CountDetail.objects.bulk_create(count_details)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 514, in bulk_create
    returned_columns = self._batched_insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1287, in _batched_insert
    inserted_rows.extend(self._insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1358, in as_sql
    value_rows = [
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\fields\__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\fields\__init__.py", line 1427, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\fields\__init__.py", line 1421, in get_prep_value
    value = timezone.make_aware(value, default_timezone)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\utils\timezone.py", line 242, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pytz\tzinfo.py", line 363, in localize
    raise AmbiguousTimeError(dt)
pytz.exceptions.AmbiguousTimeError: 2018-10-28 02:00:00
```
je relance...

**Comment by marioba** [comment]
No, don't restart it now. It will not finish if you restart it.

**Comment by marioba** [comment]
I have to implement it as a single command first.

**Comment by spch-GL** [comment]
j'avais déjà relancé (à 15:15:33) et je n'ai toujours pas de message d'erreur

**Comment by spch-GL** [comment]
Ca s'est replanté au même endroit... 

```
Applying comptages.0022_auto_20211217_0624...starting logger
Start with count_aggregate_value_cls table
Total rows: 1799760
0
1000
...
531000
532000
Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\operations\special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_TST/python/plugins\comptages\datamodel\migrations\0022_auto_20211217_0624.py", line 47, in migrate_data
    CountDetail.objects.bulk_create(count_details)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 514, in bulk_create
    returned_columns = self._batched_insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1287, in _batched_insert
    inserted_rows.extend(self._insert(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1358, in as_sql
    value_rows = [
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\sql\compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\fields\__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\fields\__init__.py", line 1427, in get_db_prep_value
    value = self.get_prep_value(value)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\models\fields\__init__.py", line 1421, in get_prep_value
    value = timezone.make_aware(value, default_timezone)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\utils\timezone.py", line 242, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pytz\tzinfo.py", line 363, in localize
    raise AmbiguousTimeError(dt)
pytz.exceptions.AmbiguousTimeError: 2018-10-28 02:00:00
```

Pourrais-tu faire en sorte que le script ne recommence pas à 0 à chaque fois ?

**Comment by marioba** [comment]
Version v0.10.8 should manage this migration way better.
- Logs are printed immediately to show what's happening
- Every 1000 records the data is committed to the database and the old rows are deleted, so it is possible to restart the migration if it didn't finish the first time and it will continue without restarting from the beginning
- Ambiguous times (due to daylight saving time transitions) are managed

**Comment by spch-GL** [comment]
I'm running the script since 15 minutes and there is only 1 message logged:
![image](https://user-images.githubusercontent.com/26377323/152754613-2f928864-c483-435c-80a6-a530932b4b06.png)
Is there a way to refresh the console ?

**Comment by spch-GL** [comment]
Le script 0022_auto_20211217_0624 a passé, mais ca s'est planté dans 0025_auto_20220204_1353:
`
# Console Python
# Utilisez iface pour accéder à l'interface API QGIS ou tapez help(iface) pour plus d'informations
# Avertissement de sécurité : la saisie de commandes provenant d'une source non fiable peut nuire à votre ordinateur
from django.core.management import call_command
call_command('migrate', 'comptages')
Operations to perform:
  Apply all migrations: comptages
Running migrations:
  Applying comptages.0022_auto_20211217_0624...starting logger
2022-02-07 09:31:17.027778 Start with count_aggregate_value_cls table
2022-02-07 09:31:21.277857 Table CLS (1/5), migrated 1000 rows, total elapsed time 0:00:04.250079
2022-02-07 09:31:25.090379 Table CLS (1/5), migrated 2000 rows, total elapsed time 0:00:08.062601
2022-02-07 09:31:28.918560 Table CLS (1/5), migrated 3000 rows, total elapsed time 0:00:11.890782

2022-02-07 20:42:14.105301 Table SPD (5/5), migrated 7194000 rows, total elapsed time 11:10:57.077523
2022-02-07 20:42:14.120913 All tables migrated! Total elapsed time 11:10:57.093135
 OK
  Applying comptages.0023_installation_aliasOK
  Applying comptages.0024_category_trashOK
  Applying comptages.0025_auto_20220204_1353...Traceback (most recent call last):
  File "C:\apps\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\migrations\operations\models.py", line 528, in database_forwards
    alter_together(
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\base\schema.py", line 415, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\django\db\backends\base\schema.py", line 451, in _delete_composed_index
    raise ValueError("Found wrong number (%s) of constraints for %s(%s)" % (
ValueError: Found wrong number (0) of constraints for model_class(id_model, id_class)
`

**Comment by spch-GL** [comment]
yes :-)
Applying comptages.0025_auto_20220204_1353 OK
Applying comptages.0026_alter_modelclass_id OK

But for the production DB, it would be nice to find a way to refresh the console even thow it's frozen or to prevent it to freeze or to put the logs in a file...

**Comment by marioba** [comment]
The python console and QGIS are running in the same thread, so when the python console is completely busy, QGIS doesn't refresh the console (at least on Windows, on Linux it still refreshes it sometimes).

I changed the migration_0022 again in version 0.10.11. 
Now the log is written into a file called `migration_0022.log`.

When I launch the migration from QGIS, the log file is created into my home directory. If you want you can also define a path for the file directly into the migration file [comptages/datamodel/migrations/0022_auto_20211217_0624.py](https://github.com/opengisch/OpenComptage/blob/3550f36b8f7a0c89fb6dbea1a5685cdbdbe04a1f/comptages/datamodel/migrations/0022_auto_20211217_0624.py#L12), line 12.
