### ISSUE TITLE
Perte de connexion

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#259]
Depuis quelque temps, un souci de perte de connexion survient parfois, et cela vient de m'arriver alors que les index venaient d'être créés :
> 2022-07-04T15:40:17     INFO    2022-07-04 15:40:17.024637 - Generate report action started
> 2022-07-04T15:40:26     INFO    2022-07-04 15:40:26.102612 - Generate report action can really begin now for count 765 with file_path: L:/Devel/Inf_Technique/Comptage/OpenComptage/_P_10.03
> 2022-07-04T15:44:04     INFO    2022-07-04 15:44:04.790697 - Report generation _P_10.03 ended with errors: **ERREUR: perte de la connexion au processus parallèle**
>              
> 2022-07-04T15:44:04     INFO    2022-07-04 15:44:04.806253 - All tasks ended 

Dans les logs, il semble que Django perde cette connexion:
```
2022-07-04T15:44:04     WARNING    Une erreur est survenue lors de l'éxécution du code Python:
             
             
             django.db.utils.OperationalError: ERREUR: perte de la connexion au processus parallèle
             
             
             
             Traceback (most recent call last):
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
              return self.cursor.execute(sql, params)
             psycopg2.errors.ObjectNotInPrerequisiteState: ERREUR: perte de la connexion au processus parallèle
             
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\report_task.py", line 28, in run
              raise e
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\report_task.py", line 24, in run
              report.prepare_reports(self.file_path, self.count, self.year, self.template, self.section_id, callback_progress=self.setProgress)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\report.py", line 24, in prepare_reports
              _prepare_default_reports(file_path, count, template_path, callback_progress)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\report.py", line 52, in _prepare_default_reports
              _data_speed(count, section, monday, workbook)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\report.py", line 585, in _data_speed
              df = statistics.get_average_speed_by_hour(
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\comptages\core\statistics.py", line 361, in get_average_speed_by_hour
              df = pd.DataFrame.from_records(qs.values('hour', 'speed'))
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\frame.py", line 2222, in from_records
              arrays, arr_columns = to_arrays(data, columns)
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\internals\construction.py", line 829, in to_arrays
              if not len(data):
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 262, in __len__
              self._fetch_all()
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 1324, in _fetch_all
              self._result_cache = list(self._iterable_class(self))
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 109, in __iter__
              for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1130, in results_iter
              results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
              cursor.execute(sql, params)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 66, in execute
              return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
              return executor(sql, params, many, context)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
              return self.cursor.execute(sql, params)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\utils.py", line 90, in __exit__
              raise dj_exc_value.with_traceback(traceback) from exc_value
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\django\db\backends\utils.py", line 84, in _execute
              return self.cursor.execute(sql, params)
             django.db.utils.OperationalError: ERREUR: perte de la connexion au processus parallèle
             
             
             
             
             
             Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
             
             
             Version de QGIS : 3.24.3-Tisler Tisler, cf22b74e
             
             
             Chemin Python :
             
             C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\vmDeportWSIC:/apps/OSGeo4W/apps/qgis/./pythonC:/Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:/Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/pluginsC:/apps/OSGeo4W/apps/qgis/./python/pluginsC:\apps\OSGeo4W\bin\python39.zipC:\apps\OSGeo4W\apps\Python39\DLLsC:\apps\OSGeo4W\apps\Python39\libC:\apps\OSGeo4W\binC:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packagesC:\apps\OSGeo4W\apps\Python39C:\apps\OSGeo4W\apps\Python39\lib\site-packagesC:\apps\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.eggC:\apps\OSGeo4W\apps\Python39\lib\site-packages\win32C:\apps\OSGeo4W\apps\Python39\lib\site-packages\win32\libC:\apps\OSGeo4W\apps\Python39\lib\site-packages\PythonwinC:/Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

Penses-tu que ce soit un problème avec
- la version de Django ?
- la version de notre BD ?
- le taux d'occupation de PG ?
- autre idée ?

Stéphane est en vacances actuellement, il aura peut-être des idées à son retour

Voici un exemple plus ancien:
![image](https://user-images.githubusercontent.com/26377323/177173609-fb476840-039d-4b11-8324-7b175005243e.png)

**Comment by marioba** [comment]
Je ne sais pas exactement, mais il me semble que c'est un problème de Postgres. Cela arrive-t-il sur toutes les bases de données ?
