### ISSUE TITLE
v0.10.17: beaucoup d'erreur Python lors de la génération des graphiques

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#265]
Premier test dans ma base de DEV avec le fichier de l'issue 117:
```
2022-07-07T07:59:29     INFO    2022-07-07 07:59:29.997273 - Prepare import file 00107600_Clusette_Brot-Dsous.txt started
2022-07-07T07:59:30     INFO    2022-07-07 07:59:30.012899 - Prepare import file 00107600_Clusette_Brot-Dsous.txt
2022-07-07T07:59:30     INFO    2022-07-07 07:59:30.012899 - Import file 00107600_Clusette_Brot-Dsous.txt started
2022-07-07T07:59:54     INFO    2022-07-07 07:59:54.678019 - Import file 00107600_Clusette_Brot-Dsous.txt ended
2022-07-07T07:59:54     INFO    2022-07-07 07:59:54.693646 - All tasks ended
2022-07-07T07:59:54     INFO    2022-07-07 07:59:54.693646 - Generate validation chart started
2022-07-07T08:00:03     INFO    2022-07-07 08:00:03.474963 - Debug_GL: Graphique démarré
2022-07-07T08:01:06     INFO    2022-07-07 08:01:06.130120 - Reject data started
2022-07-07T08:01:06     INFO    2022-07-07 08:01:06.864417 - Generate validation chart started
2022-07-07T08:01:07     INFO    2022-07-07 08:01:07.161291 - Generate validation chart ended : No data to validate
2022-07-07T08:01:07     INFO    2022-07-07 08:01:07.161291 - Reject data ended
```
On constate que la ligne "Generate validation chart ended" manque

Les graphiques s'affichent presque correctement, avec 2 directions mais:
- l'avertissement suivante survient 670 fois, dans les logs "Erreur Python"
voici le premier:
```
2022-07-07T08:00:03     WARNING    Traceback (most recent call last):
              File "pandas\_libs\tslibs\timezones.pyx", line 266, in pandas._libs.tslibs.timezones.get_dst_info
             AttributeError: 'NoneType' object has no attribute 'total_seconds'

```
voici le dernier:
```
2022-07-07T08:00:21     WARNING    Traceback (most recent call last):
              File "pandas\_libs\tslibs\timezones.pyx", line 266, in pandas._libs.tslibs.timezones.get_dst_info
             AttributeError: 'NoneType' object has no attribute 'total_seconds'

```
Ensuite vient un avertissement plus détaillé:
```
 2022-07-07T08:00:22     WARNING    Traceback (most recent call last):
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\comptages.py", line 284, in all_tasks_finished
              self.chart_dock.show_next_quarantined_chart()
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\chart\chart_dialog.py", line 247, in show_next_quarantined_chart
              self.set_attributes(quarantined_counts[0])
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\chart\chart_dialog.py", line 58, in set_attributes
              self._populate_tab(tab, section, count)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\chart\chart_dialog.py", line 151, in _populate_tab
              ChartTjm(
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\chart\chart_dialog.py", line 291, in get_div
              fig = px.bar(
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\plotly\express\_chart_types.py", line 365, in bar
              return make_figure(
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\plotly\express\_core.py", line 2114, in make_figure
              trace.update(patch)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\plotly\basedatatypes.py", line 5084, in update
              BaseFigure._perform_update(self, dict1, overwrite=overwrite)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\plotly\basedatatypes.py", line 3921, in _perform_update
              plotly_obj[key] = val
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\plotly\basedatatypes.py", line 4819, in __setitem__
              self._set_prop(prop, value)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\plotly\basedatatypes.py", line 5158, in _set_prop
              val = validator.validate_coerce(val)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\_plotly_utils\basevalidators.py", line 401, in validate_coerce
              v = copy_to_readonly_numpy_array(v)
              File "C:\Users\GrelletP\AppData\Roaming\Python\Python39\site-packages\_plotly_utils\basevalidators.py", line 107, in copy_to_readonly_numpy_array
              v = v.dt.to_pydatetime()
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\indexes\accessors.py", line 238, in to_pydatetime
              return self._get_values().to_pydatetime()
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\indexes\extension.py", line 95, in method
              result = attr(self._data, *args, **kwargs)
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\arrays\datetimes.py", line 1071, in to_pydatetime
              return ints_to_pydatetime(self.asi8, tz=self.tz)
              File "pandas\_libs\tslibs\vectorized.pyx", line 158, in pandas._libs.tslibs.vectorized.ints_to_pydatetime
              File "pandas\_libs\tslibs\timezones.pyx", line 266, in pandas._libs.tslibs.timezones.get_dst_info
             AttributeError: 'NoneType' object has no attribute 'total_seconds'

```
Là rien n'est affiché dans la fenêtre des graphiques jusqu'à ce que je clique sur un onglet (Par catégorie) puis je consulte les autres et lorsque je clique sur l'onglet  "Par TJM, direction 1" le graphique ne change pas et une autre erreur s'affiche: 
```
2022-07-07T08:00:58     WARNING    Traceback (most recent call last):
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\chart\chart_dialog.py", line 176, in chart_selection_changed
              tab.webView.setHtml(tab.charts[row])
             IndexError: list index out of range
```
Et les onglets "Par TJM, direction 2" et "Par TJM, section" sont absents
![image](https://user-images.githubusercontent.com/26377323/177709167-ad02807c-2d8d-4d00-8d2c-1d995681011a.png)

**Comment by spch-GL** [comment]
Désolé, tout ça est lié aux mises-à-jour que j'ai faites (`pip install --upgrade icalendar nose2 wheel openpyxl psycopg2 django pandas`) surement à pandas, pas au plug-in... 
En faisant un `pip install -r requirements.txt` tout est rentré dans l'ordre :-)
