### ISSUE TITLE
Cas spéciaux: la création du rapport ne produit que celui relatif à la première section

### ISSUE THREAD

**Issue by spch-GL** [opengisch/OpenComptage#278]
**Describe the bug**
La création du rapport ne produit que ceux relatifs à la première section. Il n'y a pas de rapport produit pour les autres sections.
Par contre la génération des graphiques fonctionne correctement et montre bien toutes les sections, chacune dans son onglet.

**To Reproduce**
1. Sélectionner un tronçon d'un cas spécial
2. Click sur 'Modifier comptage'
3. Click droit sur le numéro du comptage
4. Click sur 'Creer un rapport'
5. Choisir le dossier de destination
6. See error

**Expected behavior**
La création du rapport pour un cas spécial devrait générer un fichier par semaine et par section. 

**Version on which you encounter the issue:** 
- QGIS version and plugin version: QGIS 3.22 / plugin v2.1 & 2.1.1
- DB version and installation: PostgreSQL 15.0 - PostGIS 3.3.1 on remote TEST DB &  PostgreSQL 11.5 - PostGIS 2.5.3 on local DEV DB

**Comment by spch-GL** [comment]
Petite précision: cela fonctionne vite et bien avec la version du plug-in 0.10.17 sur notre base distante de prod

**Comment by spch-GL** [comment]
Encore une précision: sur ma base de DEV, j'ai utilisé le plug-in V2.1.1 pour importer les données. Comme les rapports ne sont pas tous générés avec cette version, j'ai utilisé ensuite la version 0.10.17 pour créer les rapports et cela a fonctionné vite et bien

**Comment by why-not-try-calmer** [comment]
J'ai un souci pour reproduire le problème: le jeu de données ne concerne que le tronçon `00107695` qui n'est pas un cas spécial. Est-ce que par hasard tu aurais un jeu de données pour cas spéciaux?

**Comment by spch-GL** [comment]
Voici des données pour un comptage du 15.03.2021 au 28.03.2021 sur un autre cas spécial  
[5350_1_4.zip](https://github.com/opengisch/OpenComptage/files/13447701/5350_1_4.zip)

**Comment by spch-GL** [comment]
Désolé, j'avais omis de mentionner un troncon dans mes 2 commentaires précédents, je les ai donc édités...

**Comment by spch-GL** [comment]
le plug-in devrait nous proposer de créer les rapports de chacune des sections concernées. 
Supposons un comptages de 2 semaines sur un cas spécial de 3 sections, il faudrait alors qu'il propose la création de 6 rapports

Est-ce que cette réponse pourrait-être celle attendue ?

**Comment by why-not-try-calmer** [comment]
> le plug-in devrait nous proposer de créer les rapports de chacune des sections concernées. Supposons un comptages de 2 semaines sur un cas spécial de 3 sections, il faudrait alors qu'il propose la création de 6 rapports
> 
> Est-ce que cette réponse pourrait-être celle attendue ?

Oui c'est plus clair; mais comment le plugin devrait formuler cette proposition? Même logique que pour les 100 jours valides, à savoir un check au moment de l'exportation avec une fenêtre de sélection pour les sections concernées? Oubien faut-il tout simplement, en général, toujours produire les rapports correspondant à chaque section?

**Comment by why-not-try-calmer** [comment]
(cont) A titre d'exemple le rapports annuel du 53526896 pour l'année 2021 produit 45 fichiers.

**Comment by spch-GL** [comment]
> > le plug-in devrait nous proposer de créer les rapports de chacune des sections concernées. Supposons un comptages de 2 semaines sur un cas spécial de 3 sections, il faudrait alors qu'il propose la création de 6 rapports
> > Est-ce que cette réponse pourrait-être celle attendue ?
> 
> Oui c'est plus clair; mais comment le plugin devrait formuler cette proposition? Même logique que pour les 100 jours valides, à savoir un check au moment de l'exportation avec une fenêtre de sélection pour les sections concernées? Oubien faut-il tout simplement, en général, toujours produire les rapports correspondant à chaque section?

Il me semble qu'il y a une confusion: Pour moi, la sélection avec les cases à cocher (section puis dates), c'est justement pour la production des rapports

**Comment by why-not-try-calmer** [comment]
> (cont) A titre d'exemple le rapports annuel de la section `53526896` pour l'année 2021 produit 45 fichiers.

D'accord. Alors le but du jeu pour moi actuellement, c'est de prouver qu'il manque des fichiers lorsqu'on génère des rapports hebdomadaires et des rapports annuels portant sur la section `53526896`. Est-ce que les données que tu m'as transmises dans ce fil de discussion seront suffisantes pour ce faire?

**Comment by spch-GL** [comment]
J'ai trouvé des données d'un cas spécial annuel (2021), mais il y a plus de 100 M et j'ai utilisé 7zip pour spliter en 4, puis ajouté l'extension `.txt` pour que github les accepte...
[EGAS.zip.001.txt](https://github.com/opengisch/OpenComptage/files/13478211/EGAS.zip.001.txt)
[EGAS.zip.002.txt](https://github.com/opengisch/OpenComptage/files/13478255/EGAS.zip.002.txt)
[EGAS.zip.003.txt](https://github.com/opengisch/OpenComptage/files/13478259/EGAS.zip.003.txt)
[EGAS.zip.004.txt](https://github.com/opengisch/OpenComptage/files/13478264/EGAS.zip.004.txt)

Cela concerne l'installation ci-dessous qui a 8 voies (`lane`) sur 6 tronçons (`section`)
![image](https://github.com/opengisch/OpenComptage/assets/26377323/37d9714b-8d00-4e96-9b99-bfc643237671)
Pour pouvoir importer les données, il faut que l'alias soit EGAS

Voici l'extrait de la table lane qui les concerne:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GrelletP/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GrelletP/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


id | number | direction | direction_desc | id_installation | id_section
-- | -- | -- | -- | -- | --
17514 | 1 | 1 |   | 8768 | 00056200
17515 | 2 | 2 |   | 8768 | 00056200
17516 | 3 | 1 |   | 8768 | 00056202
17517 | 4 | 2 |   | 8768 | 00056202
17518 | 5 | 1 |   | 8768 | 53316875
17519 | 6 | 1 |   | 8768 | 53326880
17520 | 7 | 1 |   | 8768 | 53336885
17521 | 8 | 1 |   | 8768 | 53346890



</body>

</html>

Je viens de les importer dans ma base de DEV et cela a fonctionné:
![image](https://github.com/opengisch/OpenComptage/assets/26377323/11a35c0b-4ae0-459e-a066-3fa7ced34a7c)

**Comment by spch-GL** [comment]
Tu constateras que 

1. pendant l'importation (via le bouton de la barre d'outil, sélectionner tous les fichiers) qGis se fige
2. il faut accepter les données pour chaque section séparément (c'est voulu) mais c'est à chaque fois assez long. Probablement qu'il recalcule l'affichage pour tous les onglets et pas seulement celui qu'on vient d'accepter.
3. il revient sur le premier onglet même si ce n'est pas celui que l'on vient d'accepter
4. il n'y a pas de données pour la voie 7 (section 53336885) mais c'est un problème vraisemblablement un problème de capteur

**Comment by spch-GL** [comment]
j'ai essayé de générer un rapport annuel en sélectionnant le tronçon 53326880, et cela a provoqué cette erreur:
```
2023-11-27T18:36:45     WARNING    Une erreur est survenue lors de l'exécution du code Python :
             
             
             KeyError: 'date'
             
             
             Traceback (most recent call last):
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3800, in get_loc
              return self._engine.get_loc(casted_key)
              File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
              File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
              File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
              File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
             KeyError: 'date'
             
             The above exception was the direct cause of the following exception:
             
             Traceback (most recent call last):
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\core\report_task.py", line 28, in run
              raise e
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\core\report_task.py", line 24, in run
              report.prepare_reports(self.file_path, self.count, self.year, self.template, self.section_id, callback_progress=self.setProgress)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\core\report.py", line 33, in prepare_reports
              _prepare_yearly_report(file_path, year, template_path, section_id, callback_progress)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\core\report.py", line 75, in _prepare_yearly_report
              _data_day_yearly(count, section, year, workbook)
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\core\report.py", line 436, in _data_day_yearly
              df = statistics.get_time_data_yearly(
              File "C:\Users/GrelletP/AppData/Roaming/QGIS/QGIS3\profiles\cptg_dev/python/plugins\comptages\core\statistics.py", line 86, in get_time_data_yearly
              df = df.groupby([df['date'].dt.dayofweek, 'hour']).thm.sum()
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\frame.py", line 3805, in __getitem__
              indexer = self.columns.get_loc(key)
              File "C:\apps\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
              raise KeyError(key) from err
             KeyError: 'date'
             
             
             
             
             Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
             
             
             Version de QGIS : 3.28.11-Firenze Firenze, b02458a196


```

**Comment by spch-GL** [comment]
j'ai encore essayé de générer les rapports hebdomadaires en sélectionnant le même tronçon (53326880), et après 5 minutes il avait déjà généré 8 rapports, mais tous sur la section 00056200, exemple:
[00056200_20210118_r.xlsx](https://github.com/opengisch/OpenComptage/files/13478564/00056200_20210118_r.xlsx)

**Comment by why-not-try-calmer** [comment]
Merci!

**Comment by why-not-try-calmer** [comment]
Hum attention tout le contenu est tronqué: 

![image](https://github.com/opengisch/OpenComptage/assets/19554213/780f89aa-98ed-436b-8564-5ac25e7cd60c)

Tu peux m'envoyer le tout non-compressé ou non suffixé en ZIP en utilisant https://www.swisstransfer.com/fr-ch s'il-te-plaît?

**Comment by spch-GL** [comment]
Pour les utiliser avec 7Zip, il suffit de les placer les 4 dans un même dossier et de les renommer en supprimant l'extension .txt
![image](https://github.com/opengisch/OpenComptage/assets/26377323/5d6ac2d4-dfd2-440d-9739-7a0128cd808c)

Ensuite ouvrir n'importe lequel avec 7Zip.

Mais je vais te faire un transfert avec notre système: webtransfer.ne.ch qui t'avertira par courriel lorsque cela sera prêt

**Comment by spch-GL** [comment]
Pas résolu par la version 2.1.2: il ne produite que le rapport que sur la première section
